name: CICD

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Instal dependencies and run tests
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/next' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        id: semantic-release
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: Install pip & build package
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
      - name: Upload package to PYPI
        if: steps.semantic-release.outputs.released == 'true'
        run: |
          python3 -m pip install twine==6.0.1
          python3 -m twine upload --repository pypi dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
   